[build]
builder = "dockerfile"

[deploy]
startCommand = "python manage.py collectstatic --noinput && gunicorn stress_analyzer.wsgi:application --bind 0.0.0.0:$PORT"

[[services]]
name = "web"
httpPort = 8000
